#!/usr/bin/env python3
"""Compile design/tokens.json into zero2w_console/static/tokens.css."""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "design", "tokens.json")
OUT = os.path.join(ROOT, "zero2w_console", "static", "tokens.css")

# A "." is legal in a token name but must be escaped in a CSS custom property.
esc = lambda n: n.replace(".", r"\.")

FAMILIES = ["spacing", "radius", "stroke", "opacity"]


def theme_value(tok, theme, first):
    v = tok.get("value")
    if isinstance(v, dict):
        return v.get(theme, v.get(first))
    return v  # a plain string belongs to the first theme


def main():
    with open(SRC) as fh:
        d = json.load(fh)

    themes = [t["id"] for t in d["color"]["themes"]]
    first = themes[0]
    out = [
        "/* GENERATED by scripts/build_tokens.py from design/tokens.json — do not edit. */",
        "/* Design system: Auto-Blox */",
        "",
    ]

    def emit_theme_block(selector, theme):
        rows = []
        for tok in d["color"]["tokens"]:
            val = theme_value(tok, theme, first)
            if val:
                rows.append("  --%s: %s;" % (esc(tok["name"]), val))
        for tok in d.get("shadow", {}).get("tokens", []):
            val = theme_value(tok, theme, first)
            if val:
                rows.append("  --%s: %s;" % (esc(tok["name"]), val))
        out.append("%s {\n%s\n}\n" % (selector, "\n".join(rows)))

    emit_theme_block(':root, [data-theme="%s"]' % first, first)
    for theme in themes[1:]:
        emit_theme_block('[data-theme="%s"]' % theme, theme)

    # Theme-independent scales.
    rows = []
    for fam in FAMILIES:
        if fam not in d:
            continue
        for tok in d[fam]["tokens"]:
            rows.append("  --%s: %s;" % (esc(tok["name"]), tok["value"]))
    for key, stack in d["type"]["families"].items():
        rows.append("  --font-%s: %s;" % (key, stack))
    out.append(":root {\n%s\n}\n" % "\n".join(rows))

    # One class per type style.
    prop = {
        "fontSize": "font-size", "lineHeight": "line-height", "fontWeight": "font-weight",
        "letterSpacing": "letter-spacing", "fontStyle": "font-style",
    }
    for group in d["type"]["groups"]:
        fam = group.get("family", "ui")
        for st in group["styles"]:
            decls = ["  font-family: var(--font-%s);" % st.get("family", fam)]
            for k, css in prop.items():
                if k in st:
                    decls.append("  %s: %s;" % (css, st[k]))
            out.append(".%s {\n%s\n}\n" % (esc(st["name"]), "\n".join(decls)))

    css = "\n".join(out)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(css)

    n_colors = len(d["color"]["tokens"])
    n_styles = sum(len(g["styles"]) for g in d["type"]["groups"])
    print("wrote %s (%d bytes): %d colors x %d themes, %d type styles"
          % (OUT, len(css), n_colors, len(themes), n_styles))
    # Guard: nothing should reference a var() we did not define.
    defined = set(re.findall(r"^\s*--([A-Za-z0-9_.\\-]+):", css, re.M))
    print("   defined custom properties:", len(defined))


if __name__ == "__main__":
    sys.exit(main())
